// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBup1JJbIH6lyhfLLvwe-TIUConKnGiBR0',
    appId: '1:406424447366:web:cad8c39019e2bbbed26407',
    messagingSenderId: '406424447366',
    projectId: 'football-app-837f2',
    authDomain: 'football-app-837f2.firebaseapp.com',
    storageBucket: 'football-app-837f2.firebasestorage.app',
    measurementId: 'G-330B6YJC27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCjACdb5BOHdsSh3JJAlA8LaywtbuVX8',
    appId: '1:406424447366:android:57bbd718c001a7b7d26407',
    messagingSenderId: '406424447366',
    projectId: 'football-app-837f2',
    storageBucket: 'football-app-837f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgHd3pWpac9jHlgOqMj5QVB0ZEREbe4A',
    appId: '1:406424447366:ios:03f1735ed53ab481d26407',
    messagingSenderId: '406424447366',
    projectId: 'football-app-837f2',
    storageBucket: 'football-app-837f2.firebasestorage.app',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgHd3pWpac9jHlgOqMj5QVB0ZEREbe4A',
    appId: '1:406424447366:ios:03f1735ed53ab481d26407',
    messagingSenderId: '406424447366',
    projectId: 'football-app-837f2',
    storageBucket: 'football-app-837f2.firebasestorage.app',
    iosBundleId: 'com.example.footballApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBup1JJbIH6lyhfLLvwe-TIUConKnGiBR0',
    appId: '1:406424447366:web:1663c5e329403045d26407',
    messagingSenderId: '406424447366',
    projectId: 'football-app-837f2',
    authDomain: 'football-app-837f2.firebaseapp.com',
    storageBucket: 'football-app-837f2.firebasestorage.app',
    measurementId: 'G-094RY85SMR',
  );
}
